### ISSUE TITLE
Greeter Screen

### ISSUE THREAD

**Issue by ABHISHEK-AMRUTE** [ABHISHEK-AMRUTE/Flutter-News-App#3]
Design a simple Greeter Screen, which can be used for the first time launch of the App.
It must include input from the user to enter country name. 
This will be helpful to provide news feeds.

**Comment by SwaroopSambhayya** [comment]
I can work on this,assign it to me

**Comment by ABHISHEK-AMRUTE** [comment]
Issue assigned to you. If the case of any issue, share that on telegram group(Link in the readme.md)
